
services:

  vertx:
    container_name: vertx
    #build: .
    #image: skionus/vertx-mid:dev
    image: vertx-api:dev
    #restart: unless-stopped
    ports:
      - 8080:8081
    environment:
      APP_BIND_ADDRESS: "0.0.0.0"
      APP_BIND_PORT: "8081"
      # KEYCLOAK_BASE_URL: "http://auth.local"
      KEYCLOAK_BASE_URL: "http://keycloak.local:3000/auth"
      KEYCLOAK_REALM: "vertx"
      KEYCLOAK_CLIENT_ID: "vertx-service"
      KEYCLOAK_CLIENT_SECRET: "ecb85cc5-f90d-4a03-8fac-24dcde57f40c"
      # LOGI_BACKEND_HOST: "atarcdb3.postgres.database.azure.com"
      LOGI_BACKEND_HOST: "192.168.57.35"
      LOGI_BACKEND_PORT: "5432"
    # volumes:
    #   - /home/toor/Downloads/DigiCertGlobalRootCA.crt.pem:/application/DigiCertGlobalRootCA.crt.pem:ro
